### ISSUE TITLE
info.plist utility error

### ISSUE THREAD

**Issue by fkjadoon94** [MatVre/MiBeaconTrilaterationDemo#6]
"The file “MiBeaconTrilaterationDemoTests-Info.plist” couldn’t be opened because there is no such file."

Any idea why the code is not not compiling? Didn't the last merge fix the issue?

**Comment by MatVre** [comment]
Maybe delete the test target?




Best,

Mathijs

**Comment by fkjadoon94** [comment]
Works. Thanks!
